// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPpXvqp-JnnBxktNdgr9lntOf-FwtjKfo',
    appId: '1:72373035853:web:86fdf0b36fe6bff2da8d04',
    messagingSenderId: '72373035853',
    projectId: 'tungtee-9b10a',
    authDomain: 'tungtee-9b10a.firebaseapp.com',
    storageBucket: 'tungtee-9b10a.appspot.com',
    measurementId: 'G-V7LSR9DXBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByE9uB1ayaq-Vo2FClWzPN-jGMZoyIE-0',
    appId: '1:72373035853:android:13eba04cd661e370da8d04',
    messagingSenderId: '72373035853',
    projectId: 'tungtee-9b10a',
    storageBucket: 'tungtee-9b10a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkGcd09N_jRPoq4MpKi9NaEdlDOsgP7z0',
    appId: '1:72373035853:ios:9d063ce1aac2568eda8d04',
    messagingSenderId: '72373035853',
    projectId: 'tungtee-9b10a',
    storageBucket: 'tungtee-9b10a.appspot.com',
    iosClientId: '72373035853-dhn5fl8co22fqp2n4i6lf8t4afhahsnj.apps.googleusercontent.com',
    iosBundleId: 'com.example.tungtee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkGcd09N_jRPoq4MpKi9NaEdlDOsgP7z0',
    appId: '1:72373035853:ios:9d063ce1aac2568eda8d04',
    messagingSenderId: '72373035853',
    projectId: 'tungtee-9b10a',
    storageBucket: 'tungtee-9b10a.appspot.com',
    iosClientId: '72373035853-dhn5fl8co22fqp2n4i6lf8t4afhahsnj.apps.googleusercontent.com',
    iosBundleId: 'com.example.tungtee',
  );
}
